<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<RootNamespace>comprehensure</RootNamespace>
		<RootNamespace>comprehensure</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<ApplicationTitle>comprehensure</ApplicationTitle>

		<ApplicationId>com.companyname.comprehensure</ApplicationId>

		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<UserSecretsId>671f96e0-63a1-4701-b472-ececb786110d</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<MauiAsset Include="Resources\Raw\quiz1data.json" />
		<MauiAsset Include="Resources\Raw\quiz2data.json" />
		<MauiAsset Include="Resources\Raw\quiz3data.json" />
		<MauiAsset Include="Resources\Raw\quiz4data.json" />
		<MauiAsset Include="Resources\Raw\quiz5data.json" />
		<MauiAsset Include="Resources\Raw\quiz6data.json" />
		<MauiAsset Include="Resources\Raw\quiz7data.json" />
		<MauiAsset Include="Resources\Raw\quiz8data.json" />
	</ItemGroup>
	
	<ItemGroup>
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" />

		<MauiSplashScreen Include="Resources\Splash\appicon.svg" Color="#F2F6FB" BaseSize="128,128" />

		<MauiImage Include="Resources\Images\**\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		<MauiImage Update="Resources\Images\m1_curiosity_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m1_curiosity_2.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m1_curiosity_3.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m1_curiosity_4.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m1_history_1.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m1_history_2.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m1_history_3.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m1_history_4.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m1_knowledge_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m1_knowledge_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m1_knowledge_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m1_knowledge_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m2_message_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m2_message_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m2_message_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m2_message_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m2_patience_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m2_patience_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m2_patience_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m2_patience_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m2_wisdom_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m2_wisdom_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m2_wisdom_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m2_wisdom_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m3_balance_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m3_balance_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m3_balance_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m3_balance_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m3_hidden_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m3_hidden_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m3_hidden_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m3_hidden_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m3_vision_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m3_vision_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m3_vision_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m3_vision_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m4_harmony_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m4_harmony_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m4_harmony_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m4_harmony_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m4_investigation_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m4_investigation_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m4_investigation_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m4_investigation_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m4_revelation_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m4_revelation_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m4_revelation_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m4_revelation_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m5_anticipation_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m5_anticipation_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m5_anticipation_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m5_anticipation_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m5_continuity_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m5_continuity_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m5_continuity_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m5_continuity_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m5_intention_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m5_intention_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m5_intention_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m5_intention_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m6_awareness_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m6_awareness_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m6_awareness_3.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m6_awareness_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m6_discipline_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m6_discipline_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m6_discipline_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m6_discipline_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m6_vulnerability_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m6_vulnerability_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m6_vulnerability_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m6_vulnerability_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m7_preservation_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m7_preservation_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m7_preservation_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m7_preservation_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m7_reciprocation_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m7_reciprocation_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m7_reciprocation_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m7_reciprocation_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m7_resonance_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m7_resonance_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m7_resonance_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m7_resonance_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m8_introspection_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m8_introspection_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m8_introspection_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m8_introspection_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m8_stagnation_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m8_stagnation_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m8_stagnation_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m8_stagnation_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m8_surrender_1.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m8_surrender_2.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m8_surrender_3.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>
		<MauiImage Update="Resources\Images\m8_surrender_4.jpg.jpg">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</MauiImage>

		<MauiFont Include="Resources\Fonts\*" />

		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <AndroidResource Remove="DASHBOARD\NewFolder1\**" />
	  <Compile Remove="DASHBOARD\NewFolder1\**" />
	  <EmbeddedResource Remove="DASHBOARD\NewFolder1\**" />
	  <MauiCss Remove="DASHBOARD\NewFolder1\**" />
	  <MauiXaml Remove="DASHBOARD\NewFolder1\**" />
	  <None Remove="DASHBOARD\NewFolder1\**" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Resources\Raw\LocalDB\ACCOUNTS\Accounts.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui" Version="9.1.1" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="FirebaseAuthentication.net" Version="4.1.0" />
		<PackageReference Include="FirebaseDatabase.net" Version="5.0.0" />
		<PackageReference Include="Google.Cloud.Firestore" Version="4.2.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="MainPages\LoginPage.xaml.cs">
			<DependentUpon>LoginPage.xaml</DependentUpon>
		</Compile>
		<Compile Update="MainPages\SignUpPage.xaml.cs">
			<DependentUpon>SignUpPage.xaml</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<MauiXaml Update="DASHBOARD\AboutUs.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\AllAboutUS_Dashboard.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\ChangePassword.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\DictionaryPage3.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\DictionaryPage4.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\DictionaryPage5.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\DictionaryPage6.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\DictionaryPage7.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\DictionaryPage8.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\FlashScreen.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\HelpPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\MainDashboard.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\MiniGames\OneThemePage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\MiniGames\OneThemeWindow.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\MiniGames\SynonymHuntPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\MiniGames\SynonymHuntWindow.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\ModulesDashboard.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\ProfileDashboard.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\ProgressDashboard.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\StoryPage\DictionaryPage2.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\StoryPage\DictionaryPage3.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\StoryPage\DictionaryPage4.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\StoryPage\DictionaryPage5.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\StoryPage\DictionaryPage6.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\StoryPage\DictionaryPage7.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\StoryPage\DictionaryPage8.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\StoryPage\NewContent1.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="DASHBOARD\UsernameReq.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="FlashScreen.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="MainPages\LoginPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="MainPages\SignUpPage.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="SplashScreenPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="DASHBOARD\StoryPage\ViewModels\quiz\quizdata\" />
		<Folder Include="DASHBOARD\StoryPage\ViewModels\stories\" />
		<Folder Include="Resources\Images\Progress_bar\" />
		<Folder Include="Resources\Raw\Firebase_api\API_KEY\" />
	</ItemGroup>
	<ItemGroup>
		<MauiAsset Include="Resources\Raw\secrets.json" />
	</ItemGroup>
	<ItemGroup>
		<None Update="Resources\Raw\secrets.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>